import { EventItem, Organizer, Ticket } from '../types';

export const INITIAL_ORGANIZERS: Organizer[] = [
  {
    id: 'org-tech-sa',
    email: 'contact@sdaia.gov.sa',
    name: 'المهندس عبد الله الشمري',
    phone: '+966 50 111 2233',
    organization_name: 'الهيئة للفعاليات والمؤتمرات التقنية',
    logo_url: '/logo.png',
    created_at: '2026-08-01T08:00:00Z',
    payment_methods: {
      stripe: {
        enabled: true,
        publishable_key: 'pk_live_51Mza...sdaia_live',
        account_id: 'acct_sdaia_tech_2026',
        currency: 'SAR',
      },
      bankak: {
        enabled: true,
        account_number: '2840195',
        account_name: 'شركة تنظيم الفعاليات والمؤتمرات',
        phone_number: '0912345678',
        instructions: 'يرجى إرسال إشعار التحويل عبر التطبيق لتوثيق التذكرة فورياً',
      },
      vodafone_cash: {
        enabled: true,
        wallet_number: '01012345678',
        wallet_name: 'مؤسسة الفعاليات',
        instructions: 'تحويل كاش على المحفظة مع إرفاق رقم العملية',
      },
    },
  },
  {
    id: 'org-rotana-live',
    email: 'info@rotanalive.com',
    name: 'سالم الهندي',
    phone: '+966 55 222 3344',
    organization_name: 'مجموعة روتانا للترفيه والموسيقى',
    logo_url: '/logo.png',
    created_at: '2026-08-15T10:00:00Z',
    payment_methods: {
      stripe: {
        enabled: true,
        publishable_key: 'pk_live_8849...rotana',
        account_id: 'acct_rotana_live',
        currency: 'USD',
      },
      bankak: {
        enabled: true,
        account_number: '3190842',
        account_name: 'مجموعة روتانا للصوتيات',
        phone_number: '0998765432',
      },
      vodafone_cash: {
        enabled: true,
        wallet_number: '01099887766',
        wallet_name: 'روتانا كاش',
      },
    },
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-riyadh-tech-2026',
    organizer_id: 'org-tech-sa',
    organizer_name: 'الهيئة للفعاليات والمؤتمرات التقنية',
    title: 'مؤتمر الذكاء الاصطناعي والتقنية المتقدمة 2026',
    tagline: 'أكبر تجمع لخبراء التقنية ورواد الذكاء الاصطناعي في الشرق الأوسط',
    description: 'انضم إلينا في ثلاث أيام من الإلهام والابتكار، حيث يلتقي أكثر من 50 متحدثاً عالمياً لمناقشة مستقبل الذكاء الاصطناعي التوليدي، الحوسبة السحابية، وإنترنت الأشياء مع ورش عمل تطبيقية وجلسات تواصل حصرية.',
    category: 'technology',
    venue_name: 'مركز الملك عبد العزيز الدولي للمؤتمرات',
    city: 'الرياض',
    country: 'المملكة العربية السعودية',
    currency: 'ر.س',
    currency_code: 'SAR',
    address: 'طريق الملك عبد العزيز، الرياض، المملكة العربية السعودية',
    start_date: '2026-11-15T09:00:00Z',
    end_date: '2026-11-17T18:00:00Z',
    logo_url: '/logo.png',
    banner_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80',
    ticket_bg_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80',
    ticket_theme: 'royal_gold',
    total_capacity: 1500,
    status: 'published',
    featured: true,
    created_at: '2026-09-01T10:00:00Z',
    ticket_tiers: [
      {
        id: 'tier-riyadh-general',
        event_id: 'evt-riyadh-tech-2026',
        name: 'تذكرة عامة - General Pass',
        price: 150,
        capacity: 1000,
        sold_count: 642,
        perks: [],
        color_hex: '#3b82f6',
        is_active: true,
      },
      {
        id: 'tier-riyadh-vip',
        event_id: 'evt-riyadh-tech-2026',
        name: 'تذكرة كبار الشخصيات - VIP Pass',
        price: 450,
        capacity: 350,
        sold_count: 280,
        perks: [],
        color_hex: '#f59e0b',
        is_active: true,
      },
      {
        id: 'tier-riyadh-workshop',
        event_id: 'evt-riyadh-tech-2026',
        name: 'تذكرة ورش العمل المتقدمة',
        price: 300,
        capacity: 150,
        sold_count: 115,
        perks: [],
        color_hex: '#10b981',
        is_active: true,
      },
    ],
  },
  {
    id: 'evt-music-nights-2026',
    organizer_id: 'org-rotana-live',
    organizer_name: 'مجموعة روتانا للترفيه والموسيقى',
    title: 'ليالي طرب الأصالة والموسيقى العربية',
    tagline: 'أمسية موسيقية استثنائية مع كوكبة من نجوم الفن الأصيل',
    description: 'عيشوا أجواء ساحرة مع أروع المعزوفات الموسيقية الشرقية والأغاني الخالدة بقيادة نخبة من المايسترو والفرق الموسيقية العالمية في ليلة لا تُنسى تحت أضواء النجوم.',
    category: 'music',
    venue_name: 'مسرح محمد عبده أرينا - بوليفارد سيتي',
    city: 'الرياض',
    address: 'بوليفارد رياض سيتي، الرياض',
    start_date: '2026-10-28T20:30:00Z',
    end_date: '2026-10-28T23:45:00Z',
    logo_url: '/logo.png',
    banner_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&auto=format&fit=crop&q=80',
    ticket_bg_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&auto=format&fit=crop&q=80',
    ticket_theme: 'festive_hologram',
    total_capacity: 3000,
    status: 'published',
    featured: true,
    created_at: '2026-09-10T12:00:00Z',
    country: 'المملكة العربية السعودية',
    currency: 'ر.س',
    currency_code: 'SAR',
    ticket_tiers: [
      {
        id: 'tier-music-bronze',
        event_id: 'evt-music-nights-2026',
        name: 'الفئة البرونزية',
        price: 180,
        capacity: 1500,
        sold_count: 1100,
        perks: [],
        color_hex: '#94a3b8',
        is_active: true,
      },
      {
        id: 'tier-music-silver',
        event_id: 'evt-music-nights-2026',
        name: 'الفئة الفضية',
        price: 320,
        capacity: 1000,
        sold_count: 850,
        perks: [],
        color_hex: '#cbd5e1',
        is_active: true,
      },
      {
        id: 'tier-music-royal',
        event_id: 'evt-music-nights-2026',
        name: 'الفئة الملكية Royal Box',
        price: 850,
        capacity: 500,
        sold_count: 490,
        perks: [],
        color_hex: '#eab308',
        is_active: true,
      },
    ],
  },
  {
    id: 'evt-dubai-future-2026',
    organizer_id: 'org-tech-sa',
    organizer_name: 'الهيئة للفعاليات والمؤتمرات التقنية',
    title: 'قمة دبي لمستقبل التكنولوجيا والابتكار 2026',
    tagline: 'منصة الابتكار الأولى في الشرق الأوسط لعالم التكنولوجيا',
    description: 'ملتقى عالمي في دبي يجمع نخبة المبتكرين والشركات الناشئة والمستثمرين العالميين لمناقشة أحدث تقنيات المستقبل والبلوكشين والذكاء الاصطناعي.',
    category: 'technology',
    venue_name: 'مركز دبي التجاري العالمي (DWTC)',
    city: 'دبي',
    country: 'الإمارات العربية المتحدة',
    currency: 'د.إ',
    currency_code: 'AED',
    address: 'شارع الشيخ زايد، دبي، الإمارات العربية المتحدة',
    start_date: '2026-12-05T09:00:00Z',
    end_date: '2026-12-07T17:00:00Z',
    logo_url: '/logo.png',
    banner_url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&auto=format&fit=crop&q=80',
    ticket_bg_url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&auto=format&fit=crop&q=80',
    ticket_theme: 'neon_cyber',
    total_capacity: 2000,
    status: 'published',
    featured: true,
    created_at: '2026-09-12T10:00:00Z',
    ticket_tiers: [
      {
        id: 'tier-dubai-general',
        event_id: 'evt-dubai-future-2026',
        name: 'تذكرة الدخول العام (General Pass)',
        price: 250,
        capacity: 1500,
        sold_count: 720,
        perks: [],
        color_hex: '#06b6d4',
        is_active: true,
      },
      {
        id: 'tier-dubai-vip',
        event_id: 'evt-dubai-future-2026',
        name: 'تذكرة كبار الشخصيات (VIP Pass)',
        price: 750,
        capacity: 500,
        sold_count: 290,
        perks: [],
        color_hex: '#f59e0b',
        is_active: true,
      },
    ],
  },
  {
    id: 'evt-khartoum-expo-2026',
    organizer_id: 'org-tech-sa',
    organizer_name: 'الهيئة للفعاليات والمؤتمرات التقنية',
    title: 'معرض الخرطوم الدولي للتقنية وريادة الأعمال',
    tagline: 'ملتقى المبدعين ورواد الأعمال وصناع المستقبل في السودان',
    description: 'أكبر معرض تقني وتجاري لرواد الأعمال والمشاريع الناشئة والتحول الرقمي في السودان مع ورش عمل تفاعلية وفرص استثمارية واعدة.',
    category: 'business',
    venue_name: 'أرض المعارض الدولية - بري',
    city: 'الخرطوم',
    country: 'جمهورية السودان',
    currency: 'ج.س',
    currency_code: 'SDG',
    address: 'بري، الخرطوم، السودان',
    start_date: '2026-11-20T10:00:00Z',
    end_date: '2026-11-23T20:00:00Z',
    logo_url: '/logo.png',
    banner_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
    ticket_bg_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
    ticket_theme: 'arabic_heritage',
    total_capacity: 1200,
    status: 'published',
    featured: true,
    created_at: '2026-09-14T08:00:00Z',
    ticket_tiers: [
      {
        id: 'tier-sd-regular',
        event_id: 'evt-khartoum-expo-2026',
        name: 'تذكرة دخول يومية',
        price: 5000,
        capacity: 900,
        sold_count: 430,
        perks: [],
        color_hex: '#10b981',
        is_active: true,
      },
      {
        id: 'tier-sd-vip',
        event_id: 'evt-khartoum-expo-2026',
        name: 'تذكرة شاملة كبار الشخصيات',
        price: 15000,
        capacity: 300,
        sold_count: 140,
        perks: [],
        color_hex: '#eab308',
        is_active: true,
      },
    ],
  },
  {
    id: 'evt-cairo-startup-2026',
    organizer_id: 'org-rotana-live',
    organizer_name: 'مجموعة روتانا للترفيه والموسيقى',
    title: 'قمة القاهرة للشركات الناشئة والابتكار 2026',
    tagline: 'ملتقى ريادة الأعمال وصناع التغيير في مصر والمنطقة',
    description: 'قمة سنوية تجمع رواد الأعمال والمستثمرين وحاضنات الأعمال في القاهرة لاستعراض أحدث الأفكار والحلول التقنية والابتكارية.',
    category: 'business',
    venue_name: 'مركز مصر للمعارض الدولية (EIEC)',
    city: 'القاهرة',
    country: 'جمهورية مصر العربية',
    currency: 'ج.م',
    currency_code: 'EGP',
    address: 'محور المشير طنطاوي، التجمع الخامس، القاهرة',
    start_date: '2026-12-10T09:30:00Z',
    end_date: '2026-12-12T18:30:00Z',
    logo_url: '/logo.png',
    banner_url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&auto=format&fit=crop&q=80',
    ticket_bg_url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&auto=format&fit=crop&q=80',
    ticket_theme: 'royal_gold',
    total_capacity: 2500,
    status: 'published',
    featured: true,
    created_at: '2026-09-15T09:00:00Z',
    ticket_tiers: [
      {
        id: 'tier-cairo-general',
        event_id: 'evt-cairo-startup-2026',
        name: 'تذكرة حضور عامة',
        price: 350,
        capacity: 1800,
        sold_count: 980,
        perks: [],
        color_hex: '#ef4444',
        is_active: true,
      },
      {
        id: 'tier-cairo-vip',
        event_id: 'evt-cairo-startup-2026',
        name: 'تذكرة كبار الزوار ورجال الأعمال',
        price: 950,
        capacity: 700,
        sold_count: 410,
        perks: [],
        color_hex: '#f59e0b',
        is_active: true,
      },
    ],
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'tkt-001-vip',
    ticket_code: 'TIK-784912-VIP',
    order_id: 'ord-1001',
    event_id: 'evt-riyadh-tech-2026',
    tier_id: 'tier-riyadh-vip',
    tier_name: 'تذكرة كبار الشخصيات - VIP Pass',
    event_title: 'مؤتمر الذكاء الاصطناعي والتقنية المتقدمة 2026',
    event_date: '2026-11-15T09:00:00Z',
    event_venue: 'مركز King Abdulaziz للمؤتمرات، الرياض',
    event_logo: '/logo.png',
    event_banner: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80',
    ticket_bg_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80',
    ticket_theme: 'royal_gold',
    buyer_name: 'سلطان بن فهد الدوسري',
    buyer_email: 'sultan.fahad@example.com',
    buyer_phone: '+966 50 123 4567',
    price: 450,
    platform_commission: 22.5,
    organizer_net_amount: 427.5,
    status: 'valid',
    created_at: '2026-09-20T14:30:00Z',
    qr_data: 'TIK-784912-VIP',
  },
];
